---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openldap
    pod-security.kubernetes.io/enforce: privileged
  name: openldap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: openldap
data:
  seed.ldif: |
    dn: dc=tanzu,dc=net
    dc: tanzu
    objectClass: dcObject
    objectClass: organization
    o: Tanzu, Inc

    dn: ou=core,dc=tanzu,dc=net
    objectClass: organizationalUnit
    ou: core

    dn: cn=platform-viewer,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: platform-viewer
    sn: platform Viewer
    uid: platform-viewer
    mail: platform-viewer@tanzu.net
    userPassword: tpsm1!

    dn: cn=platform-admin,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: platform-admin
    sn: platform Admin
    uid: platform-admin
    mail: platform-admin@tanzu.net
    userPassword: tpsm1!

    dn: cn=tpadmins,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpadmins
    description: Tanzu Platform Admins
    member: cn=platform-admin,ou=core,dc=tanzu,dc=net

    dn: cn=tpviewer,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpviewer
    description: Tanzu Platform Viewer
    member: cn=platform-viewer,ou=core,dc=tanzu,dc=net
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: openldap
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - env:
        - name: LDAP_ROOT
          value: dc=tanzu,dc=net
        - name: LDAP_ADMIN_USERNAME
          value: admin
        - name: LDAP_ADMIN_PASSWORD
          value: password
        - name: LDAP_CUSTOM_LDIF_DIR
          value: /ldifs
        image: bitnami/openldap
        imagePullPolicy: IfNotPresent
        name: openldap
        ports:
        - containerPort: 1389
          protocol: TCP
        - containerPort: 1636
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ldifs/seed.ldif
          name: ldifs-seed
          subPath: seed.ldif
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: seed.ldif
            path: seed.ldif
          name: app-config
        name: ldifs-seed
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
spec:
  type: ClusterIP
  selector:
    app: openldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 1389
      name: openldap
